# URI of your MQTT broker
broker: tcp://<ip>:<port>

# Username for MQTT (default none)
# username: "batman"

# Password for MQTT (default none)
# password: "jkrsucks420"

# Keep alive interval (seconds, default 15)
# keepalive: 20

# Global prefix for all MQTT topics (default <computername>/monitor/)
# prefix: batcave/screens/

# Reconnect on connection loss (default true)
#   Reconnection works with a random backoff algorithm, starting at
#   "backoff min" and exponentially increasing until reaching "backoff max"
#   If false, application quits on a failed connection or on connection loss.
# reconnect: false

# Reconnection minimum interval (milliseconds, default 50)
# backoff min: 10

# Reconnection maximum interval (milliseconds, default 2000)
# backoff max: 10000

# Connection timeout (seconds, default 1)
# connect timeout: 3

# Disconnection timeout (seconds, default 4)
# disconnect timeout: 2
